# Generated by Django 6.0.3 on 2026-03-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('target_ip', models.CharField(max_length=15)),
                ('encrypted_results', models.TextField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
