# Generated by Django 6.0.3 on 2026-03-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_user_scan_history_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
